plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev'
}

def gitTagProvider = providers.exec {
    commandLine 'git', 'describe', '--tags', '--abbrev=0'
}.standardOutput.asText.map { it.trim() }

def mod_version = gitTagProvider.get().replaceFirst('^v', '')
version = mod_version
group = mod_group_id

base {
    archivesName = mod_file_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "org.appliedenergistics:appliedenergistics2:26.1.10-beta"
    implementation "org.appliedenergistics:guideme:26.1.12-beta"
    implementation "curse.maven:glodium-957920:8196173"
    implementation "curse.maven:applied-flux-965012:8246560"
    implementation "curse.maven:ex-pattern-provider-892005:8237330"
    implementation "curse.maven:geckolib-388172:8327201"
    implementation "curse.maven:advancedae-1084104:8383853"
    implementation "maven.modrinth:jade:26.1.8+neoforge"
    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:26.1.819"
    compileOnly "mezz.jei:jei-26.1.2-neoforge:29.12.0.41"

    switch (use_Xei) {
        case "emi":
            break
        case "rei":
            runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:26.1.819"
            runtimeOnly "dev.architectury:architectury-neoforge:20.0.7"
            runtimeOnly "curse.maven:cloth-config-348521:7817583"
            break
        case "jei":
            runtimeOnly "mezz.jei:jei-26.1.2-neoforge:29.12.0.41"
    }

}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_issue_url          : mod_issue_url,
                             mod_display_url        : mod_display_url,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description,
                             ae2_version_range      : ae2_version_range,
                             appflux_version_range  : appflux_version_range,
                             glodium_version_range  : glodium_version_range,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

jar {
    archiveBaseName.set("${mod_file_name}")
    archiveVersion.set("${mod_version}+${minecraft_version}")
}