org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.76
neo_version_range=[26.1.2.76,)
loader_version_range=[4,)
mod_id=appgen
mod_file_name=applied-generators
mod_name=Applied Generators
mod_license=All Rights Reserved
mod_issue_url=https://github.com/sapporo1101/AppliedGenerators/issues
mod_display_url=https://github.com/sapporo1101/AppliedGenerators
mod_group_id=io.github.sapporo1101
mod_authors=sapporo1101
mod_description=add FE Generators for AE2
ae2_version_range=[26.1.9-alpha,)
appflux_version_range=[26.1-1.0.0-neoforge,)
glodium_version_range=[26.1-1.2-neoforge,)
use_Xei=jei