package io.github.sapporo1101.appgen.common;

import com.glodblock.github.glodium.registry.defer.DeferredDataComponentType;
import io.github.sapporo1101.appgen.common.blockentities.*;
import io.github.sapporo1101.appgen.common.blocks.*;
import io.github.sapporo1101.appgen.common.blocks.networking.FluxCellBlockItem;
import io.github.sapporo1101.appgen.common.items.CommonItem;
import io.github.sapporo1101.appgen.common.items.StackSmeltingCardItem;
import io.github.sapporo1101.appgen.menu.helper.DirectionSet;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredItem;
import org.jetbrains.annotations.NotNull;

import static appeng.block.AEBaseBlock.stoneProps;

public class AGSingletons {
    public static DeferredBlock<FluxCellBlock.@NotNull Standard> FLUX_CELL;
    public static DeferredBlock<FluxCellBlock.@NotNull Dense> DENSE_FLUX_CELL;
    public static DeferredBlock<@NotNull CreativeFluxCellBlock> CREATIVE_FLUX_CELL;
    public static DeferredBlock<@NotNull PatternBufferBlock> PATTERN_BUFFER;
    public static DeferredBlock<@NotNull GenesisSynthesizerBlock> GENESIS_SYNTHESIZER;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG1k> SINGULARITY_GENERATOR_1K;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG4k> SINGULARITY_GENERATOR_4K;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG16k> SINGULARITY_GENERATOR_16K;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG64k> SINGULARITY_GENERATOR_64K;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG256k> SINGULARITY_GENERATOR_256K;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG1m> SINGULARITY_GENERATOR_1M;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG4m> SINGULARITY_GENERATOR_4M;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG16m> SINGULARITY_GENERATOR_16M;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG64m> SINGULARITY_GENERATOR_64M;
    public static DeferredBlock<SingularityGeneratorBlock.@NotNull SG256m> SINGULARITY_GENERATOR_256M;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG1k> FLUX_GENERATOR_1K;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG4k> FLUX_GENERATOR_4K;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG16k> FLUX_GENERATOR_16K;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG64k> FLUX_GENERATOR_64K;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG256k> FLUX_GENERATOR_256K;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG1m> FLUX_GENERATOR_1M;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG4m> FLUX_GENERATOR_4M;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG16m> FLUX_GENERATOR_16M;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG64m> FLUX_GENERATOR_64M;
    public static DeferredBlock<FluxGeneratorBlock.@NotNull FG256m> FLUX_GENERATOR_256M;
    public static DeferredBlock<@NotNull EmberClusterBlock> EMBER_BUD_SMALL;
    public static DeferredBlock<@NotNull EmberClusterBlock> EMBER_BUD_MEDIUM;
    public static DeferredBlock<@NotNull EmberClusterBlock> EMBER_BUD_LARGE;
    public static DeferredBlock<@NotNull EmberClusterBlock> EMBER_CLUSTER;
    public static DeferredBlock<@NotNull BuddingEmberBlock> BUDDING_EMBER_FLAWLESS;
    public static DeferredBlock<@NotNull BuddingEmberBlock> BUDDING_EMBER_FLAWED;
    public static DeferredBlock<@NotNull BuddingEmberBlock> BUDDING_EMBER_CHIPPED;
    public static DeferredBlock<@NotNull BuddingEmberBlock> BUDDING_EMBER_DAMAGED;
    public static DeferredBlock<@NotNull Block> EMBER_BLOCK;
    public static DeferredBlock<@NotNull SmelterBlock> SMELTER;

    public static DeferredItem<@NotNull CommonItem> EMBER_CRYSTAL;
    public static DeferredItem<@NotNull CommonItem> EMBER_CRYSTAL_CHARGED;
    public static DeferredItem<@NotNull CommonItem> EMBER_DUST;
    public static DeferredItem<@NotNull CommonItem> ORIGINATION_PRINT;
    public static DeferredItem<@NotNull CommonItem> ORIGINATION_PROCESSOR;
    public static DeferredItem<@NotNull CommonItem> ORIGINATION_PRESS;
    public static DeferredItem<@NotNull CommonItem> COPPER_DUST;
    public static DeferredItem<@NotNull CommonItem> GOLD_DUST;
    public static DeferredItem<@NotNull CommonItem> NETHERITE_DUST;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_1K;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_4K;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_16K;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_64K;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_256K;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_1M;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_4M;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_16M;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_64M;
    public static DeferredItem<@NotNull CommonItem> COMPONENT_256M;
    public static DeferredItem<@NotNull StackSmeltingCardItem> STACK_SMELTING_CARD;

    public static DeferredDataComponentType<DirectionSet> DIRECTION_SET;

    public static void init(AGRegistryHandler regHandler) {
        FLUX_CELL = regHandler.block("flux_cell", FluxCellBlock.Standard::new, FluxCellBlockEntity.Standard.class, FluxCellBlockEntity.Standard::new, FluxCellBlockItem::new);
        DENSE_FLUX_CELL = regHandler.block("dense_flux_cell", FluxCellBlock.Dense::new, FluxCellBlockEntity.Dense.class, FluxCellBlockEntity.Dense::new, FluxCellBlockItem::new);
        CREATIVE_FLUX_CELL = regHandler.block("creative_flux_cell", CreativeFluxCellBlock::new, CreativeFluxCellBlockEntity.class, CreativeFluxCellBlockEntity::new, FluxCellBlockItem::new);
        PATTERN_BUFFER = regHandler.block("pattern_buffer", PatternBufferBlock::new, PatternBufferBlockEntity.class, PatternBufferBlockEntity::new);
        GENESIS_SYNTHESIZER = regHandler.block("genesis_synthesizer", GenesisSynthesizerBlock::new, GenesisSynthesizerBlockEntity.class, GenesisSynthesizerBlockEntity::new);
        SINGULARITY_GENERATOR_1K = regHandler.block("singularity_generator_1k", SingularityGeneratorBlock.SG1k::new, SingularityGeneratorBlockEntity.SG1k.class, SingularityGeneratorBlockEntity.SG1k::new);
        SINGULARITY_GENERATOR_4K = regHandler.block("singularity_generator_4k", SingularityGeneratorBlock.SG4k::new, SingularityGeneratorBlockEntity.SG4k.class, SingularityGeneratorBlockEntity.SG4k::new);
        SINGULARITY_GENERATOR_16K = regHandler.block("singularity_generator_16k", SingularityGeneratorBlock.SG16k::new, SingularityGeneratorBlockEntity.SG16k.class, SingularityGeneratorBlockEntity.SG16k::new);
        SINGULARITY_GENERATOR_64K = regHandler.block("singularity_generator_64k", SingularityGeneratorBlock.SG64k::new, SingularityGeneratorBlockEntity.SG64k.class, SingularityGeneratorBlockEntity.SG64k::new);
        SINGULARITY_GENERATOR_256K = regHandler.block("singularity_generator_256k", SingularityGeneratorBlock.SG256k::new, SingularityGeneratorBlockEntity.SG256k.class, SingularityGeneratorBlockEntity.SG256k::new);
        SINGULARITY_GENERATOR_1M = regHandler.block("singularity_generator_1m", SingularityGeneratorBlock.SG1m::new, SingularityGeneratorBlockEntity.SG1m.class, SingularityGeneratorBlockEntity.SG1m::new);
        SINGULARITY_GENERATOR_4M = regHandler.block("singularity_generator_4m", SingularityGeneratorBlock.SG4m::new, SingularityGeneratorBlockEntity.SG4m.class, SingularityGeneratorBlockEntity.SG4m::new);
        SINGULARITY_GENERATOR_16M = regHandler.block("singularity_generator_16m", SingularityGeneratorBlock.SG16m::new, SingularityGeneratorBlockEntity.SG16m.class, SingularityGeneratorBlockEntity.SG16m::new);
        SINGULARITY_GENERATOR_64M = regHandler.block("singularity_generator_64m", SingularityGeneratorBlock.SG64m::new, SingularityGeneratorBlockEntity.SG64m.class, SingularityGeneratorBlockEntity.SG64m::new);
        SINGULARITY_GENERATOR_256M = regHandler.block("singularity_generator_256m", SingularityGeneratorBlock.SG256m::new, SingularityGeneratorBlockEntity.SG256m.class, SingularityGeneratorBlockEntity.SG256m::new);
        FLUX_GENERATOR_1K = regHandler.block("flux_generator_1k", FluxGeneratorBlock.FG1k::new, FluxGeneratorBlockEntity.FG1k.class, FluxGeneratorBlockEntity.FG1k::new);
        FLUX_GENERATOR_4K = regHandler.block("flux_generator_4k", FluxGeneratorBlock.FG4k::new, FluxGeneratorBlockEntity.FG4k.class, FluxGeneratorBlockEntity.FG4k::new);
        FLUX_GENERATOR_16K = regHandler.block("flux_generator_16k", FluxGeneratorBlock.FG16k::new, FluxGeneratorBlockEntity.FG16k.class, FluxGeneratorBlockEntity.FG16k::new);
        FLUX_GENERATOR_64K = regHandler.block("flux_generator_64k", FluxGeneratorBlock.FG64k::new, FluxGeneratorBlockEntity.FG64k.class, FluxGeneratorBlockEntity.FG64k::new);
        FLUX_GENERATOR_256K = regHandler.block("flux_generator_256k", FluxGeneratorBlock.FG256k::new, FluxGeneratorBlockEntity.FG256k.class, FluxGeneratorBlockEntity.FG256k::new);
        FLUX_GENERATOR_1M = regHandler.block("flux_generator_1m", FluxGeneratorBlock.FG1m::new, FluxGeneratorBlockEntity.FG1m.class, FluxGeneratorBlockEntity.FG1m::new);
        FLUX_GENERATOR_4M = regHandler.block("flux_generator_4m", FluxGeneratorBlock.FG4m::new, FluxGeneratorBlockEntity.FG4m.class, FluxGeneratorBlockEntity.FG4m::new);
        FLUX_GENERATOR_16M = regHandler.block("flux_generator_16m", FluxGeneratorBlock.FG16m::new, FluxGeneratorBlockEntity.FG16m.class, FluxGeneratorBlockEntity.FG16m::new);
        FLUX_GENERATOR_64M = regHandler.block("flux_generator_64m", FluxGeneratorBlock.FG64m::new, FluxGeneratorBlockEntity.FG64m.class, FluxGeneratorBlockEntity.FG64m::new);
        FLUX_GENERATOR_256M = regHandler.block("flux_generator_256m", FluxGeneratorBlock.FG256m::new, FluxGeneratorBlockEntity.FG256m.class, FluxGeneratorBlockEntity.FG256m::new);
        EMBER_BUD_SMALL = regHandler.block("ember_bud_small", (props) -> new EmberClusterBlock(props, 0, 3, 4));
        EMBER_BUD_MEDIUM = regHandler.block("ember_bud_medium", (props) -> new EmberClusterBlock(props, 1, 4, 3));
        EMBER_BUD_LARGE = regHandler.block("ember_bud_large", (props) -> new EmberClusterBlock(props, 2, 5, 3));
        EMBER_CLUSTER = regHandler.block("ember_cluster", (props) -> new EmberClusterBlock(props, 3, 7, 3));
        BUDDING_EMBER_FLAWLESS = regHandler.block("budding_ember_flawless", BuddingEmberBlock::new);
        BUDDING_EMBER_FLAWED = regHandler.block("budding_ember_flawed", BuddingEmberBlock::new);
        BUDDING_EMBER_CHIPPED = regHandler.block("budding_ember_chipped", BuddingEmberBlock::new);
        BUDDING_EMBER_DAMAGED = regHandler.block("budding_ember_damaged", BuddingEmberBlock::new);
        EMBER_BLOCK = regHandler.block("ember_block", (props) -> new Block(stoneProps(props).strength(3, 8).requiresCorrectToolForDrops()));
        SMELTER = regHandler.block("smelter", SmelterBlock::new, SmelterBlockEntity.class, SmelterBlockEntity::new);

        EMBER_CRYSTAL = regHandler.item("ember_crystal", CommonItem::new);
        EMBER_CRYSTAL_CHARGED = regHandler.item("ember_crystal_charged", CommonItem::new);
        EMBER_DUST = regHandler.item("ember_dust", CommonItem::new);
        ORIGINATION_PRINT = regHandler.item("printed_origination_processor", CommonItem::new);
        ORIGINATION_PROCESSOR = regHandler.item("origination_processor", CommonItem::new);
        ORIGINATION_PRESS = regHandler.item("origination_processor_press", CommonItem::new);
        COPPER_DUST = regHandler.item("copper_dust", CommonItem::new);
        GOLD_DUST = regHandler.item("gold_dust", CommonItem::new);
        NETHERITE_DUST = regHandler.item("netherite_dust", (props) -> new CommonItem(props.fireResistant()));
        COMPONENT_1K = regHandler.item("generating_component_1k", CommonItem::new);
        COMPONENT_4K = regHandler.item("generating_component_4k", CommonItem::new);
        COMPONENT_16K = regHandler.item("generating_component_16k", CommonItem::new);
        COMPONENT_64K = regHandler.item("generating_component_64k", CommonItem::new);
        COMPONENT_256K = regHandler.item("generating_component_256k", CommonItem::new);
        COMPONENT_1M = regHandler.item("generating_component_1m", CommonItem::new);
        COMPONENT_4M = regHandler.item("generating_component_4m", CommonItem::new);
        COMPONENT_16M = regHandler.item("generating_component_16m", CommonItem::new);
        COMPONENT_64M = regHandler.item("generating_component_64m", CommonItem::new);
        COMPONENT_256M = regHandler.item("generating_component_256m", CommonItem::new);
        STACK_SMELTING_CARD = regHandler.item("stack_smelting_card", StackSmeltingCardItem::new);

        DIRECTION_SET = regHandler.comp("direction_set", DirectionSet.CODEC, DirectionSet.STREAM_CODEC);
    }
}
