name: build.yml
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.4.1'
      - name: Set Project Version
        shell: bash
        run: |
          declare GITHUB_REF_NAME=${{ github.ref_name }}
          declare VERSION=${GITHUB_REF_NAME#v}
          sed -i -r "s/^mod_version=.+$/mod_version=$VERSION/" gradle.properties
          echo $VERSION
      - name: Build with Gradle
        run: |
          gradle runData
          gradle build
      - name: Upload Build Artifacts
        run: |
          gh release create ${{ github.ref }} build/libs/*.jar \
          --title "${{ github.ref }}"
        env:
          GH_TOKEN: ${{ github.token }}